Update export-solution-on-main.yml - change back to unmanged unpack
This was because of:
  Error: Solution package type did not match requested type.
  Command line argument: Managed
  Package type: Unmanaged